from __future__ import annotations

from io import BytesIO

from fpdf import FPDF  # Generates PDF exports.
import re

from ..schemas.report import InterviewReport  # Leverages structured report payload.


class _ReportPdf(FPDF):  # Minimal PDF helper to render interview report sections.
    def header(self) -> None:  # Renders persistent header.
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "Interview Report", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self) -> None:  # Renders footer with pagination.
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        page_label = f"Page {self.page_no()}"
        self.cell(0, 10, page_label, align="C")


def render_report_pdf(report: InterviewReport) -> bytes:  # Builds a PDF for the provided report payload.
    pdf = _ReportPdf()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    _render_overview(pdf, report)
    _render_session(pdf, report)
    _render_competencies(pdf, report)
    _render_metadata(pdf, report)
    buffer = BytesIO()
    pdf.output(buffer)  # type: ignore[arg-type]
    return buffer.getvalue()


def _sanitize_text(value: str, limit: int = 90) -> str:  # Breaks long tokens to fit PDF width.
    parts: list[str] = []
    for token in re.split(r"(\s+)", value):
        if not token or token.isspace():
            parts.append(token)
            continue
        if len(token) <= limit:
            parts.append(token)
            continue
        chunks = [token[i : i + limit] for i in range(0, len(token), limit)]
        parts.append(" ".join(chunks))
    return "".join(parts)


def _cell(pdf: _ReportPdf, line_height: float, text: str) -> None:  # Writes sanitized text within page width.
    pdf.multi_cell(0, line_height, _sanitize_text(text))


def _render_overview(pdf: _ReportPdf, report: InterviewReport) -> None:  # Writes the overview section.
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Overview", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    _cell(pdf, 6, f"Report ID: {report.report_id}")
    _cell(pdf, 6, f"Generated: {report.generated_at.isoformat()}")
    _cell(pdf, 6, f"Generated By: {report.generated_by}")
    candidate = report.candidate
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Candidate", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    _cell(pdf, 6, f"{candidate.name} ({candidate.email})")
    resume = candidate.resume_summary
    _cell(pdf, 6, f"Experience Headline: {resume.headline}")
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Position", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    position = report.position
    _cell(pdf, 6, f"{position.job_title} – Req {position.requisition_id}")
    _cell(pdf, 6, f"Hiring Manager: {position.hiring_manager}")
    _cell(pdf, 6, f"Mission: {position.job_description_summary.mission}")
    pdf.ln(2)


def _render_session(pdf: _ReportPdf, report: InterviewReport) -> None:  # Writes summary of session flow.
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Session Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    outcome = report.session_summary.warmup_outcome
    _cell(pdf, 6, f"Warm-up Comfort: {outcome.comfort_score:.2f} | Ready: {outcome.ready_signal}")
    _cell(pdf, 6, f"Warm-up Notes: {outcome.notes}")
    pdf.ln(1)
    for entry in report.session_summary.competency_progress:
        pdf.set_font("Helvetica", "B", 10)
        _cell(pdf, 6, f"• {entry.title} ({entry.interview_style})")
        pdf.set_font("Helvetica", "", 10)
        _cell(pdf, 5, f"Questions: {entry.question_count} | Minutes: {entry.time_spent_minutes}")
        for highlight in entry.transcript_highlights[:3]:
            _cell(pdf, 5, f"- {highlight}")
        pdf.ln(1)
    pdf.ln(1)
    evaluation = report.overall_evaluation
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Overall Evaluation", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    _cell(
        pdf,
        6,
        f"Status: {evaluation.status} | Score: {evaluation.overall_score} | Confidence: {evaluation.confidence:.2f}",
    )
    _cell(pdf, 6, f"Next Step: {evaluation.recommended_next_step}")
    if evaluation.strengths:
        _cell(pdf, 6, "Strengths:")
        for item in evaluation.strengths[:5]:
            _cell(pdf, 5, f"- {item}")
    if evaluation.risks:
        _cell(pdf, 6, "Risks:")
        for item in evaluation.risks[:5]:
            _cell(pdf, 5, f"- {item}")
    pdf.ln(2)


def _render_competencies(pdf: _ReportPdf, report: InterviewReport) -> None:  # Writes competency breakdowns.
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Competency Results", new_x="LMARGIN", new_y="NEXT")
    for competency in report.competency_results:
        pdf.set_font("Helvetica", "B", 10)
        _cell(pdf, 6, f"{competency.title} – {competency.rating.replace('_', ' ')} ({competency.score})")
        pdf.set_font("Helvetica", "", 10)
        _cell(pdf, 5, competency.summary)
        for criterion in competency.criteria[:5]:
            _cell(pdf, 5, f"- {criterion.name}: {criterion.score}/{criterion.max_score}")
            for evidence in criterion.evidence[:2]:
                _cell(pdf, 5, f"  · {evidence}")
        pdf.ln(1)
    if report.recommendations:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Recommendations", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for item in report.recommendations[:6]:
            _cell(pdf, 5, f"- {item}")
        pdf.ln(2)


def _render_metadata(pdf: _ReportPdf, report: InterviewReport) -> None:  # Writes transcript and metadata.
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Transcript Highlights", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    for excerpt in report.transcript_digest[:6]:
        _cell(pdf, 5, f"{excerpt.timestamp} [{excerpt.stage}] {excerpt.speaker}: {excerpt.excerpt}")
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "LLM Metadata", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if not report.llm_metadata:
        _cell(pdf, 5, "No LLM metadata recorded.")
        return
    for label, meta in report.llm_metadata.items():
        _cell(pdf, 5, f"{label}: {meta.model} ({meta.route}) at {meta.timestamp.isoformat()}")
